#ifndef TOOLPATHS_C
#define TOOLPATHS_C

#define _SUPPRESS_PLIB_WARNING  // Removes spam
#define _DISABLE_OPENADC10_CONFIGPORT_WARNING
#include <xc.h>
#include <plib.h>
#include "toolpaths.h"

/*
 * Square data
 */
#define SQUARE_MID_X    (0.75*(L1+L2))
#define SQUARE_MID_Y    0.0
#define SQUARE_R        (0.1*(L1+L2))
#define SQUARE_SPEED    0.1
const element square_data[] = {
    {ELEMENT_TYPE_SET_SPEED, 2*SQUARE_SPEED},
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X-SQUARE_R, SQUARE_MID_Y-SQUARE_R},
    {ELEMENT_TYPE_DEPLOY_END_EFFECTOR},
    {ELEMENT_TYPE_DO_NOTHING, 0.5},
    {ELEMENT_TYPE_SET_SPEED, SQUARE_SPEED},
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X-SQUARE_R, SQUARE_MID_Y+SQUARE_R}, // 1
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X+SQUARE_R, SQUARE_MID_Y-SQUARE_R}, // 3
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X+SQUARE_R, SQUARE_MID_Y+SQUARE_R}, // 2
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X-SQUARE_R, SQUARE_MID_Y-SQUARE_R}, // 4
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X+SQUARE_R, SQUARE_MID_Y-SQUARE_R}, // 3
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X-SQUARE_R, SQUARE_MID_Y+SQUARE_R}, // 1
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X+SQUARE_R, SQUARE_MID_Y+SQUARE_R}, // 2
    {ELEMENT_TYPE_INTERPOLATE_POS, SQUARE_MID_X-SQUARE_R, SQUARE_MID_Y-SQUARE_R}, // 4
    {ELEMENT_TYPE_RETRACT_END_EFFECTOR},
    {ELEMENT_TYPE_DO_NOTHING, 0.5},
    {ELEMENT_TYPE_SET_SPEED, 2*SQUARE_SPEED},
    {ELEMENT_TYPE_INTERPOLATE_POS, 0.99*(L1+L2), 0.0},
    {ELEMENT_TYPE_SET_ANGLES,0.0,0.0},
    {ELEMENT_TYPE_DO_NOTHING, 0.5},
    {ELEMENT_TYPE_EXIT}
};

const toolpath_struct square_path =
    {.size = ((UINT8)sizeof(square_data)/sizeof(square_data[0])), .path = square_data};


/*
 * Line data
 */
#define LINE1_X     (0.7*(L1+L2))
#define LINE2_X     (0.8*(L1+L2))
#define LINE_LENGTH (0.2*(L1+L2))
#define LINE_SPEED 0.1 // m/s
#define INTER_LINE_SPEED (2*LINE_SPEED)
const element line_data[] = {
    {ELEMENT_TYPE_SET_SPEED, INTER_LINE_SPEED},
    {ELEMENT_TYPE_INTERPOLATE_POS, LINE2_X, LINE_LENGTH/2},
    {ELEMENT_TYPE_DEPLOY_END_EFFECTOR},
    {ELEMENT_TYPE_DO_NOTHING, 0.5},
    {ELEMENT_TYPE_SET_SPEED, LINE_SPEED},
    {ELEMENT_TYPE_INTERPOLATE_POS, LINE2_X, -LINE_LENGTH/2},
    {ELEMENT_TYPE_RETRACT_END_EFFECTOR},
    {ELEMENT_TYPE_DO_NOTHING, 0.5},
    {ELEMENT_TYPE_SET_SPEED, INTER_LINE_SPEED},
    {ELEMENT_TYPE_INTERPOLATE_POS, LINE1_X, LINE_LENGTH/2},
    {ELEMENT_TYPE_DEPLOY_END_EFFECTOR},
    {ELEMENT_TYPE_DO_NOTHING, 0.5},
    {ELEMENT_TYPE_SET_SPEED, LINE_SPEED},
    {ELEMENT_TYPE_INTERPOLATE_POS, LINE1_X, -LINE_LENGTH/2},
    {ELEMENT_TYPE_RETRACT_END_EFFECTOR},
    {ELEMENT_TYPE_DO_NOTHING, 0.5},
    {ELEMENT_TYPE_GO_TO_ABS_COMMAND, 0.0},
    {ELEMENT_TYPE_EXIT}
};

const toolpath_struct line_path =
    {.size = ((UINT8)sizeof(line_data)/sizeof(line_data[0])), .path = line_data};

#endif